# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: mixnet.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 0, "", "mixnet.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0cmixnet.proto\x12\x06mixnet""\n\x0f\x46orwardResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08"7\n\x15\x46orwardMessageRequest\x12\x0f\n\x07payload\x18\x01 \x01(\x0c\x12\r\n\x05round\x18\x02 \x01(\r2Y\n\rMixnetService\x12H\n\x0e\x46orwardMessage\x12\x1d.mixnet.ForwardMessageRequest\x1a\x17.mixnet.ForwardResponseb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "mixnet_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_FORWARDRESPONSE"]._serialized_start = 24
    _globals["_FORWARDRESPONSE"]._serialized_end = 58
    _globals["_FORWARDMESSAGEREQUEST"]._serialized_start = 60
    _globals["_FORWARDMESSAGEREQUEST"]._serialized_end = 115
    _globals["_MIXNETSERVICE"]._serialized_start = 117
    _globals["_MIXNETSERVICE"]._serialized_end = 206
# @@protoc_insertion_point(module_scope)
# @@protoc_insertion_point(module_scope)
