# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: mixnet.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 0, "", "mixnet.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0cmixnet.proto\x12\x06mixnet"7\n\x15\x46orwardMessageRequest\x12\x0f\n\x07payload\x18\x01 \x01(\x0c\x12\r\n\x05round\x18\x02 \x01(\x05"(\n\x16\x46orwardMessageResponse\x12\x0e\n\x06status\x18\x01 \x01(\t"*\n\x13PollMessagesRequest\x12\x13\n\x0b\x63lient_addr\x18\x01 \x01(\t"(\n\x14PollMessagesResponse\x12\x10\n\x08payloads\x18\x01 \x03(\x0c"$\n\x0fRegisterRequest\x12\x11\n\tclient_id\x18\x01 \x01(\t""\n\x10RegisterResponse\x12\x0e\n\x06status\x18\x01 \x01(\x08"(\n\x13WaitForStartRequest\x12\x11\n\tclient_id\x18\x01 \x01(\t"=\n\x14WaitForStartResponse\x12\r\n\x05ready\x18\x01 \x01(\x08\x12\x16\n\x0eround_duration\x18\x02 \x01(\x05"Z\n\x15PrepareMessageRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x18\n\x10recipient_pubkey\x18\x02 \x01(\x0c\x12\x16\n\x0erecipient_addr\x18\x03 \x01(\t"(\n\x16PrepareMessageResponse\x12\x0e\n\x06status\x18\x01 \x01(\x08"\x1b\n\x19\x43lientPollMessagesRequest".\n\x1a\x43lientPollMessagesResponse\x12\x10\n\x08messages\x18\x01 \x03(\t2\xb1\x02\n\tMixServer\x12O\n\x0e\x46orwardMessage\x12\x1d.mixnet.ForwardMessageRequest\x1a\x1e.mixnet.ForwardMessageResponse\x12I\n\x0cPollMessages\x12\x1b.mixnet.PollMessagesRequest\x1a\x1c.mixnet.PollMessagesResponse\x12=\n\x08Register\x12\x17.mixnet.RegisterRequest\x1a\x18.mixnet.RegisterResponse\x12I\n\x0cWaitForStart\x12\x1b.mixnet.WaitForStartRequest\x1a\x1c.mixnet.WaitForStartResponse2\xb0\x01\n\x06\x43lient\x12O\n\x0ePrepareMessage\x12\x1d.mixnet.PrepareMessageRequest\x1a\x1e.mixnet.PrepareMessageResponse\x12U\n\x0cPollMessages\x12!.mixnet.ClientPollMessagesRequest\x1a".mixnet.ClientPollMessagesResponseb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "mixnet_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_FORWARDMESSAGEREQUEST"]._serialized_start = 24
    _globals["_FORWARDMESSAGEREQUEST"]._serialized_end = 79
    _globals["_FORWARDMESSAGERESPONSE"]._serialized_start = 81
    _globals["_FORWARDMESSAGERESPONSE"]._serialized_end = 121
    _globals["_POLLMESSAGESREQUEST"]._serialized_start = 123
    _globals["_POLLMESSAGESREQUEST"]._serialized_end = 165
    _globals["_POLLMESSAGESRESPONSE"]._serialized_start = 167
    _globals["_POLLMESSAGESRESPONSE"]._serialized_end = 207
    _globals["_REGISTERREQUEST"]._serialized_start = 209
    _globals["_REGISTERREQUEST"]._serialized_end = 245
    _globals["_REGISTERRESPONSE"]._serialized_start = 247
    _globals["_REGISTERRESPONSE"]._serialized_end = 281
    _globals["_WAITFORSTARTREQUEST"]._serialized_start = 283
    _globals["_WAITFORSTARTREQUEST"]._serialized_end = 323
    _globals["_WAITFORSTARTRESPONSE"]._serialized_start = 325
    _globals["_WAITFORSTARTRESPONSE"]._serialized_end = 386
    _globals["_PREPAREMESSAGEREQUEST"]._serialized_start = 388
    _globals["_PREPAREMESSAGEREQUEST"]._serialized_end = 478
    _globals["_PREPAREMESSAGERESPONSE"]._serialized_start = 480
    _globals["_PREPAREMESSAGERESPONSE"]._serialized_end = 520
    _globals["_CLIENTPOLLMESSAGESREQUEST"]._serialized_start = 522
    _globals["_CLIENTPOLLMESSAGESREQUEST"]._serialized_end = 549
    _globals["_CLIENTPOLLMESSAGESRESPONSE"]._serialized_start = 551
    _globals["_CLIENTPOLLMESSAGESRESPONSE"]._serialized_end = 597
    _globals["_MIXSERVER"]._serialized_start = 600
    _globals["_MIXSERVER"]._serialized_end = 905
    _globals["_CLIENT"]._serialized_start = 908
    _globals["_CLIENT"]._serialized_end = 1084
# @@protoc_insertion_point(module_scope)
# @@protoc_insertion_point(module_scope)
