messages_per_round: 2
round_duration: 5
dummy_payload: dummy
mix_servers:
- id: server_1
  address: server_1:50051
- id: server_2
  address: server_2:50052
- id: server_3
  address: server_3:50053
clients:
- id: client_1
  address: client_1:50061
- id: client_2
  address: client_2:50062
